# -*- coding: utf-8 -*-
"""Care_Transition_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ELfsdvAh-jEFW93d2TwnwfTi4g-wQLQP
"""

pip install pandas numpy matplotlib plotly streamlit scikit-learn prophet

import pandas as pd

df = pd.read_csv('/content/HHS_Unaccompanied_Alien_Children_Program.csv')

df.head()

!pip install pandas numpy matplotlib plotly prophet

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

df = pd.read_csv('/content/HHS_Unaccompanied_Alien_Children_Program.csv')

df.head()

df.columns

df.info()

df['Date'] = pd.to_datetime(df['Date'])

df.isnull().sum()

df = df.fillna(0)

df.columns = [
    'date',
    'cbp_apprehended',
    'cbp_custody',
    'cbp_transferred',
    'hhs_care',
    'hhs_discharged'
]

df['transfer_efficiency'] = (
    df['cbp_transferred'] /
    df['cbp_custody']
)

cols = [
    'cbp_apprehended',
    'cbp_custody',
    'cbp_transferred',
    'hhs_care',
    'hhs_discharged'
]

for col in cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(',', '')
    )

    df[col] = pd.to_numeric(df[col])

df['throughput_rate'] = (
    df['hhs_discharged'] /
    df['cbp_apprehended']
)

df['backlog_rate'] = (
    df['cbp_apprehended'] -
    df['hhs_discharged']
)

df.head()

fig = px.line(
    df,
    x='date',
    y=[
        'cbp_apprehended',
        'cbp_transferred',
        'hhs_discharged'
    ],
    title='Daily Pipeline Movement'
)

fig.show()

fig = px.line(
    df,
    x='date',
    y='transfer_efficiency',
    title='Transfer Efficiency Over Time'
)

fig.show()

df.columns

df['discharge_effectiveness'] = (
    df['hhs_discharged'] / df['hhs_care']
)

df[['hhs_discharged','hhs_care','discharge_effectiveness']].head()

import plotly.express as px

fig = px.line(
    df,
    x='date',
    y='discharge_effectiveness',
    title='Discharge Effectiveness Over Time'
)

fig.show()

fig = px.bar(
    df,
    x='date',
    y='backlog_rate',
    title='Backlog Accumulation'
)

fig.show()

df['rolling_transfer'] = (
    df['transfer_efficiency']
    .rolling(7)
    .mean()
)

fig = px.line(
    df,
    x='date',
    y='rolling_transfer',
    title='7-Day Rolling Transfer Efficiency'
)

fig.show()

df['transfer_bottleneck'] = (
    (df['cbp_custody'] > df['cbp_custody'].mean()) &
    (df['transfer_efficiency'] < 0.5)
)

df[df['transfer_bottleneck'] == True]

df['date'].dtype

df['date'] = pd.to_datetime(df['date'], errors='coerce')

df['date'].dtype

df['month'] = df['date'].dt.to_period('M')

monthly = df.groupby('month')[['cbp_apprehended', 'hhs_discharged']].sum()
monthly

df['month'] = df['date'].dt.to_period('M')

monthly = df.groupby('month')[
    ['cbp_apprehended','hhs_discharged']
].sum()

monthly

monthly.plot(figsize=(12,6))
plt.show()

df.to_csv('cleaned_uac_dataset.csv', index=False)

